[build]
  base = "civic-connect-client"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://civicconnect-git.onrender.com/api/v1"

[[plugins]]
  package = "@netlify/plugin-nextjs"
